### PR TITLE
Calculating last staza via B, not W

### PR DESCRIPTION
**Pull request by kaydin**
This pull request should be linked to stanza # of months tracked issue.

### CODE REVIEW

**Review by slucey — COMMENTED** [review]
This looks good to me.  Do we need to worry about a situation where the "leading" stanza is not the last stanza?

**Comment by kaydin** [comment]
> This looks good to me. Do we need to worry about a situation where the "leading" stanza is not the last stanza?

Not sure!  "Leading" is always "last" in AK models (and most others?) but haven't looked around for counterexamples.  Though probably good to fix, just in case - can look at it later this week unless you get to it first.

**Comment by kaydin** [comment]
oh wait - since you order the stanzas in the lines immediately earlier, this is easy - will fix now

**Comment by kaydin** [comment]
leading to last change made, tested and pushed.

**Review by slucey — APPROVED** [review]
Looks good.

**Pull request merged**
