### PR TITLE
Added check for negative diet values

### PR DESCRIPTION
**Pull request by rklasky**
Added a check for any negative diet values. If found, a warning is presented to the user and the warning counter is incremented.

### CODE REVIEW

**Comment by rklasky** [comment]
I've fixed the gitleaks bug/failed action in my unit tests branch. When I get my current issue with testing resolved, this gitleaks error will be fixed as well.

**Comment by rklasky** [comment]
This is a duplicate of #79. I thought I was commenting on that issue and not creating a new one.

**Comment by kaydin** [comment]
Closed as duplicate

**Comment by SarahJWeisberg** [comment]
created a new pull request (89) - closing this one since it has been replaced

**Pull request closed without merging**
